---
ID: "1a1b2c3d-4e5f-4a6b-7c8d-9e0f1a2b3c4d"
Parent: "8e22d73d-f890-427b-bfc2-cc7d72c731ad"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: "/sitecore/templates/Branches/Project/click-click-launch/Solterra and Co/Add AI Config"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260216T100000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1a1b2c3d-4e5f-4a6b-7c8d-9e0f1a2b3c4e"
