---
ID: "1b2c3d4e-5f6a-4b7c-8d9e-0f1a2b3c4d5e"
Parent: "1a1b2c3d-4e5f-4a6b-7c8d-9e0f1a2b3c4d"
Template: "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f"
Path: "/sitecore/templates/Branches/Project/click-click-launch/Solterra and Co/Add AI Config/AI Config"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: AI Config
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260216T100000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1b2c3d4e-5f6a-4b7c-8d9e-0f1a2b3c4d5f"
