---
ID: "3e7f8a9b-0c1d-4e2f-3a4b-5c6d7e8f9a0b"
Parent: "3b4c5d6e-7f8a-4b9c-0d1e-2f3a4b5c6d7e"
Template: "d6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a"
Path: "/sitecore/templates/Branches/Project/click-click-launch/Alaris/Add AI Config/AI Config/Services"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260216T100000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3e7f8a9b-0c1d-4e2f-3a4b-5c6d7e8f9a0c"
