---
ID: "59dab6ec-5246-4604-9fe1-a0ad13327f24"
Parent: "bad0ef57-d3bf-4841-a7db-d6247f95f94a"
Template: "bad0ef57-d3bf-4841-a7db-d6247f95f94a"
Path: "/sitecore/templates/Project/click-click-launch/Components/Search Experience/Rendering Parameters/Search Experience Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251217T063256Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\illia.kovalenko@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\illia.kovalenko@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4d5bc6f4-b416-4990-927c-1dcbcf8c993b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\illia.kovalenko@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T063256Z